---
name: fivek
description: Opinionated Bootc Distro

base-image: ghcr.io/blue-build/base-images/fedora-kinoite-nvidia-open
image-version: latest 

modules:
  - type: files
    files:
      - source: system
        destination: / 

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship
    remove:
      packages:
        - firefox
        - firefox-langpacks 

  - type: default-flatpaks
    configurations:
      - notify: true 
        scope: system
        install: 
          - org.mozilla.firefox
          - org.gnome.Loupe
      - scope: user 

  - type: signing 
