---
name: fivek
description: Opinionated Bootc Distro

base-image: ghcr.io/blue-build/base-images/fedora-kinoite-nvidia-open
image-version: latest 

modules:
  - type: files
    files:
      - source: system
        destination: / 

  - type: os-release
    properties:
      ID: 5k
      NAME: 5K
      PRETTY_NAME: 5K

  - type: dnf
    repos:
      files:
        - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
      nonfree: negativo17
    install:
      packages:
        - dnf-plugins-core
        - brave-origin
        - steam
        - steam-devices
        - https://vencord.dev/download/vesktop/amd64/rpm
        - cava
    remove:
      packages:
        - firefox
        - firefox-langpacks 

  - type: default-flatpaks
    configurations:
      - notify: true 
        scope: system
        install: 
          - org.vinegarhq.Sober
      - scope: user 

  - type: signing 
